### PR TITLE
Change parsing of the CPU block to have optional mpuPresent and

### LINKED ISSUE #300: [svd parser] CPU block incorrectly requires mpuPresent and fpuPresent elements
I noticed a discrepancy between the documentation and the actual SVD schema for these 2 elements; see Open-CMSIS-Pack/svd-spec#32

I've send a PR to update the documentation to conform to the SVD schema. This change also needs a loosening in the svd-parser here... Default to `false` if these elements are not present.

### PR DESCRIPTION
**Pull request by xoriath**
fpuPresent elements

Per the SVD schema; these 2 elements are actually optional. However the documentation page for the schema incorrectly claims them to be required.

Modify the parser to allow these to be optional when parsing.

Fixes #300

### CODE REVIEW

File: svd-rs/src/cpu.rs [hunk 1]
```diff
@@ -159,13 +159,13 @@ impl CpuBuilder {
         self
     }
     /// Set the mpu_present of the cpu.
-    pub fn mpu_present(mut self, value: bool) -> Self {
-        self.mpu_present = Some(value);
+    pub fn mpu_present(mut self, value: Option<bool>) -> Self {
```
Comment (burrbull) [inline svd-rs/src/cpu.rs]: This looks like a breaking change. Could we use `impl Into<Option<bool>>` or something to get around the problem?

**Review by burrbull — APPROVED** [review]

**Comment by xoriath** [comment]
What happened to the merge checks ?

**Comment by xoriath** [comment]
Thanks @burrbull !
